#!/bin/bash

from=$(dirname "$0")

if [[ "$from" -ef "." ]]; then
    echo "Run $0 from the directory where you want symlinks created."
    exit 1
fi

symlink() {
    local file=$1 base=$2

    if [[ -e "$base" ]]; then
        if [[ ! -h "$base" ]]; then
            mv -v "$base" "$(dirname "$base")/renamed-old-$(basename "$base")"
        elif [[ -d "$base" ]]; then
            # If it exists *and* is a symlinked dir, then the below ln
            # -vsf will put a symlink inside the dir instead of
            # overwriting it.
            rm "$base"
        fi
    fi
    ln -vsf "$file" "$base"
}

shopt -s dotglob
for file in "$from"/*; do
    base=$(basename "$file")

    if grep "^$base$" "$from/setup-skiplist" >/dev/null; then
        continue
    fi

    if [[ -e "$file/.symlink_each" ]]; then
        mkdir -p "$base"
        for subfile in "$file"/*; do
            subfile_base=$(echo "$subfile" | sed "s#^$from/##")
            if [[ "$subfile" != "$file/.symlink_each" ]]; then
                symlink "../$subfile" "$subfile_base"
            fi
        done
    else
        symlink "$file" "$base"
    fi
done

mkdir -p "$from/seed"
find "$from/seed" -type f -print0 | while IFS= read -r -d $'\0' file; do
    relpath="$(sed "s#^$from/seed/##" <<<"$file")"

    if [ ! -f "$relpath" ]; then
        mkdir -p "$(dirname "$relpath")"
        cp -v "$file" "$relpath"
    fi
done

mkdir -p .ssh/control

"$from/.vim/update_bundles"
