#!/usr/bin/env ruby

vim_org_scripts = [
  ["gist",          "15452", "plugin"],
  ["jquery",        "12107", "syntax"],
]

require 'fileutils'
require 'open-uri'

bundles_dir = File.join(File.dirname(__FILE__), "bundle")

FileUtils.mkdir_p(bundles_dir)
FileUtils.cd(bundles_dir) do |dir|
  vim_org_scripts.each do |name, script_id, script_type|
    puts "  Downloading #{name}"
    local_file = File.join(name, script_type, "#{name}.vim")
    FileUtils.mkdir_p(File.dirname(local_file))
    File.open(local_file, "w") do |file|
      file << open("https://www.vim.org/scripts/download_script.php?src_id=#{script_id}").read
    end
  end
end
